version: '3.9'

services:
  sports:
    container_name: sports
    restart: always
    build: .
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sports
      - MONGO_INITDB_ROOT_PASSWORD=sports